from enum import IntEnum


class ChromosomeSet(IntEnum):
    MAIN = 0
    SELECT = 1
    EMIT = 2
    ACTION_PRECALCULATION_SET = 3
    SINGLE_FIELD_SELECTOR = 4
    DOUBLE_FIELD_SELECTOR = 5
    DOUBLE_FIELD_SELECTOR_AND_KEY = 6
    TRIPLE_FILED_SELECTOR = 7
    DIRECTION_SELECTOR = 8
    DIRECTION_SELECTOR_AND_KEY = 9
    RECEIVE_ENERGY = 10
    SELECT_EPIGENE = 11
    RECEPTORS = 12


class ActionSet(IntEnum):
    RESET = 0
    FIELD_SHIFT = 1
    PROJECTION = 2
    SOFTMAX = 3
    EINSUM = 4
    CONV = 5
    MOVE = 6
    MATE = 7
    ADD_EPIGENE = 8
    REMOVE_EPIGENE = 9
    LOCK = 10
    UNLOCK = 11
    TRANSFER_ENERGY = 12
    WAIT = 13
    CONCAT = 14
    MULTIPLY = 15
    ADD = 16
    BELL = 17


OP_GEN_STATE_SIZE = 16
CELL_CENTRAL_LAYER_COUNT = 8
CELL_CENTRAL_LAYER_SIZE = 32
GENERATION_KEY_SIZE = 8
ACTION_LEFT_RIGHT_RETURN = 4
ENVIRONMENT_DIMENSIONS = 4
